server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: back
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: com.back.global.jpa.config.CustomPostgreSQLDialect
        default_batch_fetch_size: 128
        jdbc:
          batch_size: 128
          order_inserts: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true
logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.orm.jdbc.batch: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  site:
    backUrl: 'http://localhost:${server.port}'
  systemMemberApiKey: "${CUSTOM__SYSTEM_MEMBER_API_KEY:system}"
  jwt:
    secretKey: "${CUSTOM__JWT__SECRET_KEY:12345678901234567890123456789012}"
  accessToken:
    expirationSeconds: 1200
